export default function SummaryModal({ summary, onClose, isLoading }) {
  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl max-w-lg w-full p-6 relative">
        {/* Close button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-gray-400 hover:text-gray-600 text-2xl leading-none"
          aria-label="Close">
          ✕
        </button>
        
        {/* Header */}
        <div className="flex items-center gap-3 mb-6">
          <div className="text-4xl">✨</div>
          <div>
            <h2 className="text-2xl font-bold text-gray-800">
              Chat Summary
            </h2>
            <p className="text-sm text-gray-500">
              AI-powered conversation summary
            </p>
          </div>
        </div>
        
        {/* Content */}
        <div className="bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50 rounded-xl p-5 mb-6 min-h-[120px]">
          {isLoading ? (
            <div className="flex flex-col items-center justify-center gap-3 py-8">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
              <p className="text-gray-600 text-sm">
                Analyzing messages with AI...
              </p>
            </div>
          ) : (
            <div>
              <p className="text-gray-700 leading-relaxed text-base">
                {summary}
              </p>
              <div className="mt-4 pt-4 border-t border-gray-200">
                <p className="text-xs text-gray-400 flex items-center gap-2">
                  <span>🤖</span>
                  <span>Generated by AI</span>
                </p>
              </div>
            </div>
          )}
        </div>
        
        {/* Footer */}
        <div className="flex justify-end gap-3">
          <button
            onClick={onClose}
            className="px-6 py-2.5 bg-gradient-to-r from-blue-500 to-purple-500 text-white rounded-lg hover:from-blue-600 hover:to-purple-600 transition-all shadow-md hover:shadow-lg font-medium">
            Got it!
          </button>
        </div>
      </div>
    </div>
  );
}